# Generated by Django 5.1.7 on 2025-12-11 01:05

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('classe', models.CharField(blank=True, max_length=100)),
                ('nivel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tendencia', models.CharField(blank=True, max_length=50)),
                ('jogador', models.CharField(blank=True, max_length=100)),
                ('atributos', models.JSONField(default=dict)),
                ('pericias', models.JSONField(blank=True, default=list)),
                ('poderes', models.JSONField(blank=True, default=list)),
                ('magias', models.JSONField(blank=True, default=list)),
                ('equipamentos', models.JSONField(blank=True, default=list)),
                ('anotacoes', models.TextField(blank=True)),
                ('pv_atual', models.IntegerField(blank=True, null=True)),
                ('pv_max', models.IntegerField(blank=True, null=True)),
                ('defesa', models.CharField(blank=True, max_length=100)),
                ('deslocamento', models.CharField(blank=True, max_length=100)),
                ('resistencias', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
